name: "grpc-server-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
  - type: log
    scan_frequency: 1s
    enabled: true
    paths:
      - /src/logs/*.log
    fields:
      - service: grpc-server
    fields_under_root: true
    json:
      keys_under_root: true
      overwrite_keys: true
      message_key: 'message'

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "grpc-server"
