services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fruitfulfriends
  adminer:
    image: adminer:latest
    ports:
      - "8888:8888"
    depends_on:
      - postgres

