env: "local"
postgres:
  postgres_url: "postgresql://postgres:postgres@localhost:5432/fruitfulfriends?sslmode=disable"
  postgres_auto_migrate: true
  postgres_migrations_path: "./migrations"
jwt:
  token_ttl: 1h
  token_key: "api_token"
grpc:
  port: 44044
  timeout: 10h
